language: node_js
node_js:
  - "0.11"
env:
  global:
    - TIMEOUT=600000
before_script:
  - sudo apt-get install subversion
  - svn -h
script: 
  - svn checkout https://svn.sinaapp.com/ecgdemo/1 sae --username cloverren@163.com --password cloverren --no-auth-cache
  - cd sae
  - mv -f ../prototype ./
  - svn add prototype
  - svn commit -m "upload new prototype" --username cloverren@163.com --password cloverren --no-auth-cache
  
