language: java
jdk:
  - oraclejdk7
before_script:
  - sudo apt-get install subversion
  - svn -h
script:
  - cd api
  - mvn install
  - cd ../web
  - mvn package
  - cd target
  - ftp ainia:ppainia@182.18.31.105
  - put web.war