language: java
jdk:
  - oraclejdk7
before_script:
  - sudo apt-get install subversion
  - svn -h
  - sudo apt-get install ftp
  - ftp -h
script:
  - cd api
  - mvn install
  - cd ../web
  - mvn package
  - cd ../
  - ls
  - chmod +x upload.sh
  - ./upload.sh
