language: node_js
node_js:
  - "0.11"
env:
  global:
    - TIMEOUT=600000
before_script:
  - sudo apt-get install subversion
  - svn -h
script: 
  - mkdir sae
  - cd sae
  - svn checkout https://svn.sinaapp.com/ecgdemo/1 target --username cloverren@163.com --password cloverren --no-auth-cache
  - svn delete prototype
  - svn commit -m "delete old file" --username cloverren@163.com --password cloverren --no-auth-cache
  - cp -f ../prototype ./prototype
  - svn add prototype
  - svn commit -m "upload new file" --username cloverren@163.com --password cloverren --no-auth-cache
  
